name: Validate changed yaml file

on:
  pull_request:
     branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          fetch-depth: 2

      - name: ChangedFiles
        id: changed-files
        run: |
           echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD  | grep '\.yml$\|\.yaml$' | xargs)" >> $GITHUB_OUTPUT
      - name: Print changed file
        run: echo "${{steps.changed-files.outputs.changed_files}}"
      - name: Linting yaml file
        if: steps.changed-files.outputs.changed_files !=''
        run: |
          echo "${{steps.changed-files.outputs.changed_files}}" | tr ' ' '\n' | while read -r file; do
             yamllint "$file"
          done
            # xargs -I {} yamllint {}


